import Foundation
import CoreGraphics
#if canImport(WebKit)
import WebKit
#endif

/// Bridge connecting Apple AI Agent frameworks (Apple Intelligence, Local LLMs, Transformers) directly to the live Sandbox runtime.
public final class AgenticBridge: @unchecked Sendable {
    private weak var engine: SandboxEngine?
    private let toolRegistry = ToolRegistryActor()
    
    public init(engine: SandboxEngine) {
        self.engine = engine
    }
    
    // MARK: - Semantic DOM Extraction
    
    /// Extracts a token-optimized semantic representation of the current DOM state for LLM context windows.
    public func captureSemanticDOM(maxTokens: Int = 4096) async throws -> String {
        guard let engine = engine else {
            throw SandboxError.engineDeallocated
        }
        
        let script = SemanticDOMExtractor.extractionScript(maxDepth: 8)
        let rawJSON = try await engine.evaluateScript(script)
        let markdown = SemanticDOMExtractor.jsonToSemanticMarkdown(rawJSON)
        return SemanticDOMExtractor.pruneToTokenBudget(markdown, maxTokens: maxTokens)
    }
    
    /// Extracts simplified JSON structure of the DOM tree.
    public func captureSemanticJSON(maxTokens: Int = 4096) async throws -> String {
        guard let engine = engine else {
            throw SandboxError.engineDeallocated
        }
        let script = SemanticDOMExtractor.extractionScript(maxDepth: 8)
        let rawJSON = try await engine.evaluateScript(script)
        return SemanticDOMExtractor.pruneToTokenBudget(rawJSON, maxTokens: maxTokens)
    }
    
    // MARK: - Agent Code Patching
    
    /// Executes a dynamic code patch generated by the Agent, capturing visual and runtime execution feedback.
    public func applyAgentCodePatch(jsDelta: String, cssDelta: String? = nil) async throws -> AgentPatchResult {
        guard let engine = engine else {
            throw SandboxError.engineDeallocated
        }
        
        let startTime = Date()
        
        var combinedScript = "(function() {\n"
        combinedScript += "  try {\n"
        if let css = cssDelta, !css.isEmpty {
            let escapedCSS = css.replacingOccurrences(of: "\\", with: "\\\\")
                .replacingOccurrences(of: "\"", with: "\\\"")
                .replacingOccurrences(of: "\n", with: "\\n")
            combinedScript += "    let style = document.createElement('style');\n"
            combinedScript += "    style.textContent = \"\(escapedCSS)\";\n"
            combinedScript += "    document.head.appendChild(style);\n"
        }
        combinedScript += "    const patchResult = (function() {\n"
        combinedScript += "      \(jsDelta)\n"
        combinedScript += "    })();\n"
        combinedScript += "    return JSON.stringify({ success: true, result: patchResult !== undefined ? String(patchResult) : 'ok' });\n"
        combinedScript += "  } catch (err) {\n"
        combinedScript += "    return JSON.stringify({ success: false, error: err.toString(), stack: err.stack });\n"
        combinedScript += "  }\n"
        combinedScript += "})()"
        
        let rawResponse = try await engine.evaluateScript(combinedScript)
        let executionTime = Date().timeIntervalSince(startTime) * 1000.0
        let isSuccess = !rawResponse.contains("\"success\":false")
        
        var errorDesc: String?
        if !isSuccess {
            errorDesc = rawResponse
        }
        
        return AgentPatchResult(
            isSuccess: isSuccess,
            executionTimeMs: executionTime,
            rawOutput: rawResponse,
            errorDescription: errorDesc
        )
    }
    
    // MARK: - Tool Management
    
    /// Registers a tool that the Sandbox or LLM can invoke.
    public func registerTool(_ tool: any SandboxAgentTool) async {
        await toolRegistry.register(tool)
        if let engine = engine {
            await engine.registerTool(tool)
        }
    }
    
    /// Executes a registered tool directly through the Agent bridge.
    public func executeTool(name: String, argumentsJSON: String) async throws -> String {
        return try await toolRegistry.execute(toolName: name, argumentsJSON: argumentsJSON)
    }
    
    /// Returns Foundation Model function tool definitions for all registered tools.
    public func getToolDefinitions() async -> [FoundationModelToolDefinition] {
        await toolRegistry.exportFoundationModelToolDefinitions()
    }
}
